### ISSUE TITLE
提交三个bug

### ISSUE THREAD

**Issue by Lijinging** [Jackeriss/gobang#2]
你好，我尝试了你的五子棋程序，发现了3个bug
1.游戏显然是无禁手模式，这种模式下六子或更多连珠也算是胜利的，游戏中并没有体现出来
2.当自己胜利时游戏进入一个“无响应”状态
3.游戏开始的时候总是感觉怪怪的，不清楚发生了什么

**Comment by Jackeriss** [comment]
你好，很抱歉，这是我很久以前做的的期中作业，因为是短时间内写出来的东西所以难免会有考虑不周的地方，但是由于时间久远且经历有限，我已经不再对其进行维护，如有需要改进的地方可以直接在此代码的基础上进行修改，谢谢你的反馈。
